name: "lint"
on: ["pull_request"]

jobs:
  lint:
    name: "Check lint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.1"
